# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bd850cbb4949165696e77c6c3f96243489c41f61702873270520b435bdbaa5ab90e5f1ea58e6caf27bf704be9fac70cbf2dd14ce52e64789af48fa082f5495b

test:
  secret_key_base: 543ffc1f9fae2a4992686830730445271c780e74be3fec0547897524341300b493dd9c8cc4e8c1ffb89e70c5a2b619baa4eb59997489d3f1a000f682257e1ed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
